// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/fiuskylab/go-mock-example/entity"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: u
func (_m *Store) CreateUser(u entity.UserRequest) (entity.UserModel, error) {
	ret := _m.Called(u)

	var r0 entity.UserModel
	if rf, ok := ret.Get(0).(func(entity.UserRequest) entity.UserModel); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(entity.UserModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.UserRequest) error); ok {
		r1 = rf(u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
